#!/usr/bin/env bash
#
# setup-workspace.sh — set up a NEW developer's machine for an existing project.
#
# The first developer ran init.sh to create the project. Everyone after runs this to
# assemble the workspace shell on their machine: write the per-machine pointer/helper files
# (CLAUDE.md / AGENTS.md / doctor.sh) that the workspace root needs, and clone the sibling repos.
#
# Multi-repo projects only. A mono-repo-for-now project (METHOD.md §7) is a single repo with
# the pointers committed inside it — just clone that repo; there's nothing to assemble here.
#
# Usage:
#   1. Clone the docs repo first, into  <workspace>/Code/<project>-docs/
#   2. From the workspace root, run:    Code/<project>-docs/scripts/setup-workspace.sh
#
set -euo pipefail

# This script takes no options. Reject anything passed rather than ignoring it, so a typo, or a
# flag meant for one of the other helpers, is a visible error instead of a silent no-op — the
# same contract check.sh already keeps. The message stays bare rather than naming a help command,
# because the helper can be reached both through ./doctor.sh and directly.
if [ "$#" -gt 0 ]; then
  echo "setup-workspace.sh: unknown option: $1" >&2
  exit 2
fi

# This script lives in Code/{{PROJECT}}-docs/scripts/ in the scaffold and in
# Code/<project>-docs/scripts/ after initialization; derive paths instead of hard-coding the
# generated project name. DOCS_REL is written into root pointers and falls back when python3
# is unavailable.
DOCS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT="$(cd "$DOCS_DIR/../.." && pwd)"
DOCS_REL="$(python3 -c "import os;print(os.path.relpath('$DOCS_DIR','$ROOT'))" 2>/dev/null || echo "Code/$(basename "$DOCS_DIR")")"
cd "$ROOT"

echo "Workspace root: $ROOT"
echo "Docs hub:       $DOCS_REL"

# --- 1. Write the per-machine root pointers/helpers --------------------------
# These are written before the clone step deliberately, but the ordering is not what makes the
# clone step safe — step 2 warns and continues instead of aborting, so it can no longer take the
# workspace down with it. The ordering is insurance against the *next* fatal path someone adds:
# whatever fails below, the contributor still ends up with AGENTS.md, CLAUDE.md and doctor.sh.
echo "Writing per-machine pointers and helpers (CLAUDE.md, AGENTS.md, doctor.sh) ..."
# The workspace root is a per-machine shell in multi-repo projects, not a durable repo. These
# pointers are regenerated locally so agents opened at the root can find the canonical docs hub.
for name in CLAUDE.md AGENTS.md; do
  cat > "$ROOT/$name" <<EOF
# $name

The canonical agent context lives in the docs repo:
**\`$DOCS_REL/AGENTS.md\`** (tool-agnostic). Read it — and the methodology it points to in
\`$DOCS_REL/METHOD.md\` — before working here.

This is a per-machine pointer (the workspace root is not a repo). Edit the canonical file
in the docs repo, not this one.
EOF
done

cat > "$ROOT/doctor.sh" <<EOF
#!/usr/bin/env bash
#
# doctor.sh — root Throughstone doctor wrapper generated by setup-workspace.sh.

set -euo pipefail

ROOT="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
SCRIPT="\$ROOT/$DOCS_REL/scripts/doctor.sh"

if [ ! -x "\$SCRIPT" ]; then
  echo "doctor.sh: dispatcher is missing or not executable: \$SCRIPT" >&2
  exit 1
fi

exec "\$SCRIPT" "\$@"
EOF
chmod +x "$ROOT/doctor.sh"

mkdir -p "$ROOT/.claude"
mkdir -p "$ROOT/.throughstone"

# --- 2. Clone sibling repos listed in the registry (if it has remotes) ------
# Nothing in this step is allowed to be fatal. A contributor who cannot reach one repository —
# or whose registry names a path this workspace has no business writing to — must still end up
# with a usable workspace, so every repo that does not arrive is reported and counted rather
# than aborting the run.
REG="$DOCS_DIR/registries/repos.yml"
missing=0
if [ -f "$REG" ]; then
  echo "Cloning sibling repos with remotes from $DOCS_REL/registries/repos.yml ..."
  # Parse repos.yml block-aware: pair each repo's own location with its own remote.
  # The registry is the multi-repo inventory, and remote: is optional. Walking each `- name:`
  # block keeps locations and remotes aligned when only some repos are cloneable; comment lines
  # and remote-less repos are skipped.
  #
  # The loop is fed by process substitution rather than a pipe for two reasons: the parser's
  # exit status stays out of the pipeline, so a registry awk cannot read is not fatal either;
  # and the loop body runs in this shell rather than a subshell, so the count below survives it.
  while IFS='|' read -r loc rem; do
    [ -n "${rem:-}" ] || continue
    # A location is meant to be a path relative to the workspace root, and one that is not never
    # gets cloned into. An absolute or `..` path can put the repository outside the workspace this
    # script is assembling, silently, whenever that path happens to be writable. The test is
    # textual on purpose: an absolute path from the first developer's machine is skipped whether
    # or not it resolves to anything here. `~` fails differently and needs its own arm — this loop
    # reads the path out of a variable, where no tilde expansion happens, so cloning it builds a
    # literal `~` directory here. The arm is quoted so the pattern matches a literal tilde.
    #
    # This runs before the existing-checkout test below, and the order is the point: on a machine
    # where a bad location does resolve — usually the one whose paths it was written from — that
    # test matches and reports the repo as already present, saying nothing about the location. The
    # machine best placed to fix the row is the one that would otherwise never hear about it.
    case "$loc" in
      /* | '~'* | .. | ../* | */../* | */..)
        echo "  skipped: $loc — a location must be a path relative to the workspace root, and this is not"
        missing=$((missing + 1))
        continue
        ;;
    esac
    # Clone side effect: create a missing sibling repo at its registry location. Existing git
    # checkouts are left untouched so rerunning setup is safe for already-cloned repos. That
    # also covers a location that is a symlink to a checkout elsewhere: -d follows the link,
    # so the repo behind it is reported and left alone rather than cloned over.
    [ -d "$loc/.git" ] && { echo "  exists: $loc"; continue; }
    echo "  cloning $rem -> $loc"
    # `--` so a value beginning with `-` reaches git as a path rather than as an option.
    git clone -q -- "$rem" "$loc" || {
      echo "  warning: could not clone $rem -> $loc — continuing without it"
      missing=$((missing + 1))
    }
  done < <(awk '
    /^[[:space:]]*#/ { next }
    /^[[:space:]]*-[[:space:]]*name:/ { if (loc != "" && rem != "") print loc "|" rem; loc=""; rem=""; next }
    /^[[:space:]]*location:/ { loc=$0; sub(/^[^:]*:[[:space:]]*"?/,"",loc); sub(/"?[[:space:]]*$/,"",loc) }
    /^[[:space:]]*remote:/   { rem=$0; sub(/^[^:]*:[[:space:]]*"?/,"",rem); sub(/"?[[:space:]]*$/,"",rem) }
    END { if (loc != "" && rem != "") print loc "|" rem }
  ' "$REG")
else
  echo "No $DOCS_REL/registries/repos.yml — skipping clone step."
fi

echo "Done. Open this folder in your agent; it will discover the context via the pointers."
if [ "$missing" -gt 0 ]; then
  echo
  echo "$missing repo(s) above did not arrive. The workspace itself is complete — fix the remote"
  echo "or the location in $DOCS_REL/registries/repos.yml, or clone the repo yourself, then re-run this"
  echo "script to pick it up."
fi
